[Task #29] Add tables of content to markdown files
AGH-Narzedzia-Informatyczne/meshi pull request #40
Opened 2020-11-19 07:46 UTC by piotrekg35

2020-11-22 23:13 UTC, Laronk requested changes

2020-11-22 23:13 UTC, Laronk commented on CONTRIBUTING.md
> +## Table of contents
ToC should be moved after "Contributing" section and the "Contributing section should be removed from the ToC.

2020-11-22 23:13 UTC, Laronk commented on CONTRIBUTING.md
> +
Each of level two and three headers should be included in the ToC with correct indentation.
Level three headers in "General rules section" should be excluded from ToC.

2020-11-22 23:13 UTC, Laronk commented on AGILE_WORKFLOW.md
> +
Each header should be included in the ToC with correct indentation.

2020-11-23 16:36 UTC, piotrekg35 commented on CONTRIBUTING.md
> +## Table of contents
Fixed. See 0a0cca534164326174e4ff38bbc4717b56003dfc

2020-11-23 16:39 UTC, piotrekg35 commented on AGILE_WORKFLOW.md
> +
Including every header would make ToC look weird. See what I've changed 0a0cca534164326174e4ff38bbc4717b56003dfc and let me know if it's ok.

2020-11-23 16:40 UTC, piotrekg35 commented on CONTRIBUTING.md
> +
Including every header would make ToC look weird. See what I've changed 0a0cca534164326174e4ff38bbc4717b56003dfc and let me know if it's ok.

2020-11-23 16:40 UTC, piotrekg35 commented on AGILE_WORKFLOW.md
> +
Fixed. See 24f064cd6cdf8a3f991a0c560a6cc2e21d4c9f2e

2020-11-23 16:50 UTC, Laronk commented on CONTRIBUTING.md
> +
Yeah, you are right. I like the solution you provided.

2020-11-23 16:51 UTC, Laronk commented on AGILE_WORKFLOW.md
> +
Nice.

2020-11-23 16:52 UTC, Laronk approved these changes
Now it looks good.

2020-11-23 18:43 UTC, danielhenel reviewed
Page scroll doesn't work:

CONTRIBUTING.md:
-Language
-Issues
-Commits
-Pull Requests

AGILE_WORKFLOW.md:
-KISS rule
-Task estimating

Please fix this

2020-11-23 20:52 UTC, merged