[Task #50] Create "meal type" section of the default page view
AGH-Narzedzia-Informatyczne/meshi pull request #59
Opened 2020-12-06 13:08 UTC by piotrekg35

2020-12-07 22:00 UTC, Aleksander2a requested changes
I think the pictures could be a bit higher (bigger) and the text should also have a different font style (in my opinion  sans-serif matches the figma design best), color (white)  and I'd make it bold and bigger just a bit, but it's up to you

2020-12-17 17:58 UTC, Laronk requested changes

2020-12-17 17:58 UTC, Laronk commented on meal_type/index.html
> +                <h3>Breakfast</h3>
The text contained in h3 html tags should have css style text-transform set to uppercase.

2020-12-17 17:58 UTC, Laronk commented on meal_type/style.css
> +html, body{
reformat file with css linter (stylelint in vscode)

2020-12-17 17:58 UTC, Laronk commented on meal_type/style.css
> +.meal{
Each CSS selector should be preceded with '#meal-types' - section id. This way after merging all the different sections together the formatting for each specific section will be applied accordingly.

2020-12-17 17:58 UTC, Laronk commented on meal_type/style.css
> +h3{
remove bottom padding from h3 tag

2020-12-17 20:25 UTC, piotrekg35 commented on meal_type/index.html
> +                <h3>Breakfast</h3>
Fixed. See 340cd012b81d32dae423998f88c8908cde57163d

2020-12-17 20:26 UTC, piotrekg35 commented on meal_type/style.css
> +html, body{
I had a problem with this one. I have downloaded a linter, but it doesn't work.

2020-12-17 20:27 UTC, piotrekg35 commented on meal_type/style.css
> +.meal{
Fixed. See 340cd012b81d32dae423998f88c8908cde57163d

2020-12-17 20:27 UTC, piotrekg35 commented on meal_type/style.css
> +h3{
Fixed. See 340cd012b81d32dae423998f88c8908cde57163d

2020-12-17 20:29 UTC, Laronk commented on meal_type/style.css
> +h3{
@piotrekg35 I meant to  write margin, sorry

2020-12-17 20:34 UTC, Laronk commented on meal_type/style.css
> +html, body{
Try this extention instead https://marketplace.visualstudio.com/items?itemName=aeschli.vscode-css-formatter

2020-12-17 20:53 UTC, piotrekg35 commented on meal_type/style.css
> +html, body{
Fixed. See 84d7be84559b28d34cea15c0ae3da8742451703b

2020-12-17 20:53 UTC, Aleksander2a approved these changes
I think it's good

2020-12-17 20:54 UTC, Laronk approved these changes
Ok

2020-12-17 20:56 UTC, merged